In [1]:
import numpy as np

v = np.array([-1, np.sin(3), 7])
print(v)
print(len(v))
print(v.shape)

[-1.          0.14112001  7.        ]
3
(3,)


In [2]:
v = np.array([-1, 2, 7])
w = np.array([2, 3,  4])
z = v + w                  # an element-by-element sum
print(z)

zz = z + 2                 # add 2 to every element of vector z
print(zz)

[ 1  5 11]
[ 3  7 13]


In [3]:
print(v[1])                # print second element in the array
v[1] = 4                   # change second element in the array to a 4
print(v)

2
[-1  4  7]


In [4]:
v_row = np.array([[1, 3, 4]])     # look closely, you'll see two square brackets instead of one
print(v_row)
v_col = np.array([[1], [3], [4]]) # now each element has its own row
print(v_col)

[[1 3 4]]
[[1]
 [3]
 [4]]


In [5]:
print(v_row + v_col)

[[2 4 5]
 [4 6 7]
 [5 7 8]]


In [6]:
# If we don't make arrays, these matrices are just treated as lists
a = [[1, 2, 3],
     [4, 5, 6]]

b = [[1, 2, 3],
     [5, 8, 13]]

a + b

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [5, 8, 13]]

In [7]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 2, 3],
              [5, 8, 13]])

print(a + b)
print(a / b)
print(a * b)
print(a @ b.T)

[[ 2  4  6]
 [ 9 13 19]]
[[1.         1.         1.        ]
 [0.8        0.625      0.46153846]]
[[ 1  4  9]
 [20 40 78]]
[[ 14  60]
 [ 32 138]]
