In [1]:
range(5)

range(0, 5)

In [2]:
def factorial(n):
    if n > 0:
        return n * factorial(n-1)
    else:
        return 1

In [3]:
import numpy as np

v = np.array([-1, np.sin(3), 7])
print(v)
print(len(v))
print(v.shape)

[-1.          0.14112001  7.        ]
3
(3,)


In [4]:
v = np.array([-1, 2, 7])
w = np.array([2, 3,  4])
z = v + w                  # an element-by-element sum
print(z)

zz = z + 2                 # add 2 to every element of vector z
print(zz)

[ 1  5 11]
[ 3  7 13]


In [5]:
print(v[1])                # print second element in the array
v[1] = 4                   # change second element in the array to a 4
print(v)

2
[-1  4  7]


In [6]:
v_row = np.array([[1, 3, 4]])     # look closely, you'll see two square brackets instead of one
print(v_row)
v_col = np.array([[1], [3], [4]]) # now each element has its own row
print(v_col)

[[1 3 4]]
[[1]
 [3]
 [4]]


In [7]:
If we now wish to perform addition and subtraction with the vectors, NumPy will show some unexpected behavior. For each row in ```v_col``` (i.e., a single scalar), it will add the full row vector of ```v_row```.

SyntaxError: invalid syntax (4203718942.py, line 1)

In [8]:
print(v_row + v_col)

[[2 4 5]
 [4 6 7]
 [5 7 8]]
